### ISSUE TITLE
Bump up adb to support android 14

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/jenkins-agent#89]
ADB version 1.0.41
Version 34.0.4-10411341

**Comment by azarouski** [comment]
`public.ecr.aws/zebrunner/jenkins-slave:2.1` was [released](https://gallery.ecr.aws/zebrunner/jenkins-slave) with
```
Android Debug Bridge version 1.0.41
Version 34.0.4-android-tools
```

**Comment by dhreben** [comment]
**Verified.**
Basic acceptance  with ,  Android-Demo-Test in Pixel_7A with android 14  successfully completed. Video, screenshots and logs are available.

```
10845905350b:~# adb
Android Debug Bridge version 1.0.41
Version 34.0.4-android-tools
Installed as /usr/bin/adb
```
